---
title: "Phyloseq PreProcessing"
author: "Andy Zhang"
date: "`r Sys.Date()`"
output: 
  html_document:
  toc: yes
  toc_float:
      collapsed: no
      smooth_scroll: yes
      toc_depth: 3
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.align = "center",
                      fig.path = "../figures/02_PreProcessing/")
```

```{r load-libraies, message=FALSE, warning=TRUE, include=FALSE}
library(devtools)
BiocManager::install("phyloseq")
library(phyloseq)

```
# Goals

Here, we will process the data into a phyloseq object.

- ASV Table
- Taxonomy table
- Track Reads(metadata)

Then we will remove the following:

1. Remove Chloroplasts
2. Remove Mitocondria
3. Remove samples without "enough reads"

Finally, write data file of phyloseq output.

# Load Data

## ASV Table
```{r load-asv-table, include=FALSE}
load("data/01_DADA2/ASV_counts.RData")

# Inspect asv_tab
head(asv_tab)[,1:5]

# Fix names
sample_names <- colnames(asv_tab)
samples_fixed <- sapply(strsplit(basename(sample_names), "_"), `[`,1) 
head(samples_fixed)

# Rewrite the ASV count file to fix names

colnames(asv_tab) <- samples_fixed 
str(asv_tab)
```

## Taxonomy Table
```{r load-tax-table}
tax_df <- read.table("data/01_DADA2/ASV_taxonomy.tsv", sep = "\t", skip = 1)
head(tax_df)

# Fix column names
/
```

## Track Reads Data
```{r load-track-reads}
```

# Handoff to phyloseq
```{r phyloseq-handoff}
``` 