---
title: "Phyloseq PreProcessing"
author: "Andy Zhang"
date: "`r Sys.Date()`"
output: 
  html_document:
  toc: yes
  toc_float:
      collapsed: no
      smooth_scroll: yes
      toc_depth: 3
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.align = "center",
                      fig.path = "../figures/02_PreProcessing/")
```

```{r load-libraies, message=FALSE, warning=TRUE, include=FALSE}
library(devtools)
BiocManager::install("phyloseq")
library(phyloseq)
library(tidyverse)
```

# Goals

Here, we will process the data into a phyloseq object.

-   ASV Table
-   Taxonomy table
-   Track Reads(metadata)

Then we will remove the following:

1.  Remove Chloroplasts
2.  Remove Mitocondria
3.  Remove samples without "enough reads"

Finally, write data file of phyloseq output.

# Load Data

## ASV Table

```{r load-asv-table, include=FALSE}
load("data/01_DADA2/ASV_counts.RData")

# Inspect asv_tab
head(asv_tab)[,1:5]

# Fix names
sample_names <- colnames(asv_tab)
samples_fixed <- sapply(strsplit(basename(sample_names), "_"), `[`,1) 
head(samples_fixed)

# Rewrite the ASV count file to fix names

colnames(asv_tab) <- samples_fixed 
str(asv_tab)
```

## Taxonomy Table

```{r load-tax-table}
tax_df <- read.table("data/01_DADA2/ASV_taxonomy.tsv", sep = "\t", skip = 1)
head(tax_df)

# Fix column names
colnames(tax_df) <- c("asv_names", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", "ASV", "ASVseq")

# Taxonomy Table Matrix
tax_mat <- 
  tax_df %>%
  tibble::column_to_rownames(., var = "asv_names") %>%
  as.matrix()
```

## Track Reads Data

```{r load-track-reads}
load("data/01_DADA2/track_read_counts.RData")

# Take a look at the data
head(track_counts_df)
dim(track_counts_df)

# Please in the terminal copy metadata.csv
# into SalinityGradient/data
# from /workdir/in_class_data_SalinityGradient_16S_metadata.csv

# Load in metadata
metadata_df <- read.csv("data/metadata.csv")
View(metadata_df)
dim(metadata_df)

# Looking at our data to see if we can merge files
colnames(metadata_df)
head(metadata_df)
head(track_counts_df)

# Merga metadata_df with track_reads_df
metadata_track_reads_df <-
  metadata_df %>%
  left_join(., track_counts_df, by = "names") %>%
  dplyr::select(-X)

# Intution Check
view(metadata_track_reads_df)

# Phyloseq requires row names

# Before
row.names(metadata_track_reads_df)
# Rewrite
row.names(metadata_track_reads_df) <- metadata_track_reads_df$names
#Check
head(metadata_track_reads_df)
```

# Handoff to phyloseq

```{r phyloseq-handoff}
# double check it's all good
dim(asv_tab)
dim(tax_mat)

# Intution Check
stopifnot(row.names(asv_tab) == row.names(tax_mat))

# Construct the phyloseq object
raw_physeq <- phyloseq(otu_table(asv_tab, taxa_are_rows = TRUE), 
                       sample_data(metadata_track_reads_df),
                       tax_table(tax_mat))
raw_physeq

# Save this raw phyloseq object
save(raw_physeq, file = "data/02_PreProcessing/raw_physeq.RData")
```
