---
title: "Biodiversity"
author: "Andy Zhang"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.path= "../figures/04_Biodiversity")
```

# Setting the Enviorment

## Set the Seed
```{r set-seed}
set.seed(218931903)
```
# Load Libraries
```{r load-libraries, include=FALSE}
library(tidyverse)
library(dada2)
library(dplyr)
library(iNEXT)
library(phyloseq)
library(patchwork)
```
# Load in Data
```{r load-data}
raw_preprocessed <-
  load("/workdir/az363/git_repos/SalinityGradient_16S/data/02_PreProcessing/raw_preprocessed_physeq.RData")


# Intutiion Check
min(sample_sums(raw_preprocessed_physeq))

# Load Colors
station_colors <- c(
  "Shipping Channel" = "dodgerblue4",
  "Aransas Bay" = "dodgerblue2",
  "Copano West" = "#D9CC3C",
  "Copano East" = "#A0E0BA",
  "Mesquite Bay" = "#00ADA7")

# Load metadata
metadata_df <-
  raw_preprocessed_physeq %>%
  sample_data() %>%
  data.frame() %>%
  View()


```
# Goals

1. Calculate the Hill Diversity of the samples
2. Evaluate the rarefraction curves
3. Evaluate the Diversity values
4. Make notes of the specfic

# Diversity Calculations with iNEXT
```{r calc-div}
iNEXT_input_df <-
  raw_preprocessed_physeq %>%
  otu_table() %>%
  data.frame()
#QUICK CHECK
#dim(iNEXT_input_df)

#iNEXT_data <-
  #iNEXT(iNEXT_input_df,
        #q = c(0,1,2), datatype = "abundance")
# Save the file
#save(iNEXT_data, file = "/workdir/az363/git_repos/SalinityGradient_16S/data/04_Biodiversity/iNext_data.RData")
```

# Evalute the Diversity
```{r load-div}
iNext_df <-
  load("/workdir/az363/git_repos/SalinityGradient_16S/data/04_Biodiversity/iNext_data.RData")
str(iNEXT_data)
typeof(iNEXT_data)
```

# Plot Diversity
```{r plot-rarefraction}
# Prepare Colors
color_df <-
  iNEXT_input_df %>%
  colnames()%>%
  data.frame()
#Check
head(color_df)
# Rename the column
colnames(color_df)[1] <- "names"
# Check
head(color_df)

# Make a helper dataframe for plotting
color_df %>%
  #Fix the names for merging
  mutate(names = gsub(names, pattern = "[.]", replace = "-"),
         names = gsub(names, pattern = "X", replace = "")) %>%
# Merge with metadata
left_join(metadata_df, by = "names") %>%
  left_join(data.frame(station_colors = station_colors,
            station = names(station_colors)),
            by = "station") %>%
head(colors_df)
  
# Merge with colors for plotting with ggiNEXT

  
  
```

# Plot Rarefaction with "ggiNEXT'
```{r ggiNEXT, fig.width =8, fig.height = 3.5}
# Plot rarefaction

# rarefaction/extrapolation curve, type = 1

# Order q:
  # 0 = Richness/ Total number of taxa
  # 1 = Exponential Shannon / "Common" taxa
  # 2 = Inverse Simpson / Number of "Dominant" taxa

ggiNEXT(iNEXT_data, type = 1, facet.var = "Order.q") +
  facet_wrap(~Order.q, scales = "fixed") +
  scale_color_manual(value = iNext_color_df) +
  scale_fill_manual(values = iNEXT_color_df$station_colors, guide = FALSE) +
  scale_shapes_manual(values = base :: rep(17, nsamples(raw_preprocessed_physeq)))


```

